parameters:
- name: TARGET_ENV
  type: string

stages:
  - stage: Deploy
    displayName: Deploy stage

    jobs:
      - deployment: Deploy
        environment: $(ADO_ENVIRONMENT_NAME)
        displayName: Deploy
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: JavaProject



                - bash: echo hello1
                - bash: echo hello2
